stages:
  - build
  - deploy

# 缓存依赖
cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

# 构建目标产物ts
build:
  image: node:10.10.0
  stage: build
  only:
    - dev
    - dev
  tags:
    - ypsx-cicd
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install --progress=false
    - npm run build
  artifacts:  
    expire_in: 1 day
    paths:
      - dist

# 部署到测试环境
deploy_dev:
  image: alpine:3.7
  stage: deploy
  only:
    - dev
  tags:
    - ypsx-cicd
  script:
    - echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ "$SERVER_USER_HOST:$SERVER_DEV_PATH"
